CREATE TABLE TB_STUDENT
(
    S_ID   VARCHAR(10) PRIMARY KEY,
    S_NAME VARCHAR(20) NOT NULL,
    SEX    VARCHAR(2)  NOT NULL
);

INSERT INTO TB_STUDENT (S_ID, S_NAME, SEX)
VALUES ('001', 'Jack', 'M ');
INSERT INTO TB_STUDENT (S_ID, S_NAME, SEX)
VALUES ('002', 'Jim', 'M ');
INSERT INTO TB_STUDENT (S_ID, S_NAME, SEX)
VALUES ('003', 'Julia', 'F ');