CREATE TABLE TB_STUDENT
(
    S_ID   VARCHAR(10) PRIMARY KEY COMMENT '学生id',
    S_NAME VARCHAR(20) NOT NULL COMMENT '学生姓名',
    SEX    VARCHAR(2)  NOT NULL COMMENT '性别'
) COMMENT '学生表';

INSERT INTO TB_STUDENT (S_ID, S_NAME, SEX)
VALUES ('001', 'Jack', 'M ');
INSERT INTO TB_STUDENT (S_ID, S_NAME, SEX)
VALUES ('002', 'Jim', 'M ');
INSERT INTO TB_STUDENT (S_ID, S_NAME, SEX)
VALUES ('003', 'Julia', 'F ');

CREATE TABLE TB_EMPLOYEE
(
    EM_NO   VARCHAR(10) PRIMARY KEY COMMENT '员工编号',
    EM_NAME VARCHAR(20) NOT NULL COMMENT '员工姓名',
    EM_SEX  VARCHAR(2)  NOT NULL COMMENT '性别',
    AGE     INTEGER     NOT NULL COMMENT '年龄'
) COMMENT '员工表';

INSERT INTO TB_EMPLOYEE (EM_NO, EM_NAME, EM_SEX, AGE)
VALUES ('001', 'Smith', 'M', 24);
INSERT INTO TB_EMPLOYEE (EM_NO, EM_NAME, EM_SEX, AGE)
VALUES ('002', 'Jack', 'M', 26);
INSERT INTO TB_EMPLOYEE (EM_NO, EM_NAME, EM_SEX, AGE)
VALUES ('003', 'Rose', 'F', 20);
INSERT INTO TB_EMPLOYEE (EM_NO, EM_NAME, EM_SEX, AGE)
VALUES ('004', 'Jane', 'F', 30);


