CREATE TABLE TB_EMPLOYEE
(
    EM_NO   VARCHAR(10) PRIMARY KEY COMMENT '员工编号',
    EM_NAME VARCHAR(20) NOT NULL COMMENT '员工姓名',
    EM_SEX  VARCHAR(2)  NOT NULL COMMENT '性别',
    AGE     INTEGER     NOT NULL COMMENT '年龄'
) COMMENT '员工表' ENGINE = InnoDB
                DEFAULT CHARSET = utf8;

INSERT INTO TB_EMPLOYEE (EM_NO, EM_NAME, EM_SEX, AGE)
VALUES ('001', 'Smith', 'M', 24);
INSERT INTO TB_EMPLOYEE (EM_NO, EM_NAME, EM_SEX, AGE)
VALUES ('002', 'Jack', 'M', 26);
INSERT INTO TB_EMPLOYEE (EM_NO, EM_NAME, EM_SEX, AGE)
VALUES ('003', 'Rose', 'F', 20);
INSERT INTO TB_EMPLOYEE (EM_NO, EM_NAME, EM_SEX, AGE)
VALUES ('004', 'Jane', 'F', 30);

CREATE TABLE SYS_LOG
(
    LOG_NO      INTEGER PRIMARY KEY AUTO_INCREMENT COMMENT '日志编号',
    USERNAME    VARCHAR(20)  NOT NULL COMMENT '操作人',
    IP          VARCHAR(64)  NOT NULL COMMENT 'IP地址',
    OPERATION   VARCHAR(50)  NOT NULL COMMENT '操作内容',
    METHOD      VARCHAR(100) NOT NULL COMMENT '请求方法',
    PARAMS      VARCHAR(300) NOT NULL COMMENT '请求参数',
    TIME        LONG         NOT NULL COMMENT '操作耗时',
    CREATE_TIME DATETIME  DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间'
) COMMENT '日志表'
    ENGINE = InnoDB
    DEFAULT CHARSET = utf8
    AUTO_INCREMENT 10000;

